# Generated by Django 5.2.6 on 2025-09-05 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0002_alter_label_color_alter_project_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('work', 'Work Session'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], help_text='Type of Pomodoro session', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='active', help_text='Current session status', max_length=15)),
                ('planned_duration', models.PositiveIntegerField(help_text='Planned session duration in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('actual_duration', models.PositiveIntegerField(blank=True, help_text='Actual session duration in minutes (when completed)', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_number', models.PositiveIntegerField(default=1, help_text='Session number in current cycle (resets after long break)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this session')),
                ('productivity_rating', models.PositiveIntegerField(blank=True, help_text='Self-rated productivity for work sessions (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, help_text='Optional task associated with this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.PositiveIntegerField(default=25, help_text='Work session duration in minutes (1-120)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('short_break_duration', models.PositiveIntegerField(default=5, help_text='Short break duration in minutes (1-60)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('long_break_duration', models.PositiveIntegerField(default=15, help_text='Long break duration in minutes (1-120)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('sessions_until_long_break', models.PositiveIntegerField(default=4, help_text='Number of work sessions before long break (2-12)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)])),
                ('auto_start_breaks', models.BooleanField(default=False, help_text='Automatically start break sessions')),
                ('auto_start_work', models.BooleanField(default=False, help_text='Automatically start work sessions after breaks')),
                ('enable_audio', models.BooleanField(default=True, help_text='Enable audio notifications')),
                ('work_sound', models.CharField(default='bell', help_text='Sound for work session completion', max_length=50)),
                ('break_sound', models.CharField(default='chime', help_text='Sound for break session completion', max_length=50)),
                ('volume', models.FloatField(default=0.7, help_text='Volume level (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable system notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pomodoro Settings',
                'verbose_name_plural': 'Pomodoro Settings',
            },
        ),
        migrations.CreateModel(
            name='PomodoroPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Preset name', max_length=100)),
                ('work_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('short_break_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('long_break_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('sessions_until_long_break', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)])),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default preset for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
