# Generated by Django 5.2.6 on 2025-09-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total time paused during session in seconds'),
        ),
    ]
