# Generated by Django 5.2.6 on 2025-09-06 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_pomodorosession_total_paused_seconds'),
        ('task', '0002_alter_label_color_alter_project_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'status'], name='pomodoro_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'started_at'], name='pomodoro_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'session_type'], name='pomodoro_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'status', 'started_at'], name='pomodoro_active_lookup_idx'),
        ),
    ]
