# Generated by Django 5.2.6 on 2025-09-05 17:30

import api.task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Hex color code (e.g., #6B7280)', max_length=7, validators=[api.task.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7, validators=[api.task.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, help_text='When to work on this task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Optional task description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Task deadline', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, help_text='Rich notes section for detailed information, similar to Notion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('P1', 'Priority 1 (Urgent)'), ('P2', 'Priority 2 (High)'), ('P3', 'Priority 3 (Medium)'), ('P4', 'Priority 4 (Low)'), ('', 'No Priority')], default='', help_text='Task priority level (P1=Urgent, P2=High, P3=Medium, P4=Low, empty=No priority)', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='The task title or name', max_length=500),
        ),
    ]
